name = "fabroses-v2"
compatibility_date = "2026-07-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "fabroses-db"
database_id = "aaa816e7-44bb-46c6-bfac-d95ef259b80e"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "fabroses-photos"
