name = "fabroses-v2"
compatibility_date = "2026-07-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "fabroses-db"
database_id = "e5642439-dffd-43b8-beff-2cc74c0e8c47"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "fabroses-photos"
