name = "fabroses-v2"
compatibility_date = "2026-07-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "fabroses-db"
database_id = "d9e82c22-24f2-4eb6-874b-b89c15ed0ce8"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "fabroses-photos"
